#include <string.h>

#include "mahoste.h"
//#include "lojban.tab.h"

struct cmm {
  const char *l;
  cmavo type;
  //enum yytokentype selmaho;
};

const struct cmm mahoste[CMAVOCNT]={
{".a",cmavo::A},
{".e",cmavo::E},
{".o",cmavo::O},
{".u",cmavo::U},
{"ji",cmavo::JI},

{"ba'i",cmavo::BAhI},
{"bai",cmavo::BAI},
{"bau",cmavo::BAU},
{"be'i",cmavo::BEhI},
{"ca'i",cmavo::CAhI},
{"cau",cmavo::CAU},
{"ci'e",cmavo::CIhE},
{"ci'o",cmavo::CIhO},
{"ci'u",cmavo::CIhU},
{"cu'u",cmavo::CUhU},
{"de'i",cmavo::DEhI},
{"di'o",cmavo::DIhO},
{"do'e",cmavo::DOhE},
{"du'i",cmavo::DUhI},
{"du'o",cmavo::DUhO},
{"fa'e",cmavo::FAhE},
{"fau",cmavo::FAU},
{"fi'e",cmavo::FIhE},
{"ga'a",cmavo::GAhA},
{"gau",cmavo::GAU},
{"ja'e",cmavo::JAhE},
{"ja'i",cmavo::JAhI},
{"ji'e",cmavo::JIhE},
{"ji'o",cmavo::JIhO},
{"ji'u",cmavo::JIhU},
{"ka'a",cmavo::KAhA},
{"ka'i",cmavo::KAhI},
{"kai",cmavo::KAI},
{"ki'i",cmavo::KIhI},
{"ki'u",cmavo::KIhU},
{"koi",cmavo::KOI},
{"ku'u",cmavo::KUhU},
{"la'u",cmavo::LAhU},
{"le'a",cmavo::LEhA},
{"li'e",cmavo::LIhE},
{"ma'e",cmavo::MAhE},
{"ma'i",cmavo::MAhI},
{"mau",cmavo::MAU},
{"me'a",cmavo::MEhA},
{"me'e",cmavo::MEhE},
{"mu'i",cmavo::MUhI},
{"mu'u",cmavo::MUhU},
{"ni'i",cmavo::NIhI},
{"pa'a",cmavo::PAhA},
{"pa'u",cmavo::PAhU},
{"pi'o",cmavo::PIhO},
{"po'i",cmavo::POhI},
{"pu'a",cmavo::PUhA},
{"pu'e",cmavo::PUhE},
{"ra'a",cmavo::RAhA},
{"ra'i",cmavo::RAhI},
{"rai",cmavo::RAI},
{"ri'a",cmavo::RIhA},
{"ri'i",cmavo::RIhI},
{"sau",cmavo::SAU},
{"si'u",cmavo::SIhU},
{"ta'i",cmavo::TAhI},
{"tai",cmavo::TAI},
{"ti'i",cmavo::TIhI},
{"ti'u",cmavo::TIhU},
{"tu'i",cmavo::TUhI},
{"va'o",cmavo::VAhO},
{"va'u",cmavo::VAhU},
{"zau",cmavo::ZAU},
{"zu'e",cmavo::ZUhE},

{"ba'e",cmavo::BAhE},
{"za'e",cmavo::ZAhE},

{"be",cmavo::BE},

{"bei",cmavo::BEI},

{"be'o",cmavo::BEhO},

{"bi'i",cmavo::BIhI},
{"bi'o",cmavo::BIhO},
{"mi'i",cmavo::MIhI},

{"bo",cmavo::BO},

{"bu",cmavo::BU},

{"ga'e",cmavo::GAhE},
{"to'a",cmavo::TOhA},
{"lo'a",cmavo::LOhA},
{"ge'o",cmavo::GEhO},
{"je'o",cmavo::JEhO},
{"jo'o",cmavo::JOhO},
{"ru'o",cmavo::RUhO},
{"se'e",cmavo::SEhE},
{"na'a",cmavo::NAhA},
{"by.",cmavo::BY},
{"cy.",cmavo::CY},
{"dy.",cmavo::DY},
{"fy.",cmavo::FY},
{"gy.",cmavo::GY},
{"jy.",cmavo::JY},
{"ky.",cmavo::KY},
{"ly.",cmavo::LY},
{"my.",cmavo::MY},
{"ny.",cmavo::NY},
{"py.",cmavo::PY},
{"ry.",cmavo::RY},
{"sy.",cmavo::SY},
{"ty.",cmavo::TY},
{"vy.",cmavo::VY},
{"xy.",cmavo::XY},
{"zy.",cmavo::ZY},
{".ybu",cmavo::YBU},
{".y'y.",cmavo::YhY},

{"ca'a",cmavo::CAhA},
{"ka'e",cmavo::KAhE},
{"nu'o",cmavo::NUhO},
{"pu'i",cmavo::PUhI},

{"cai",cmavo::CAI},
{"cu'i",cmavo::CUhI},
{"pei",cmavo::PEI},
{"ru'e",cmavo::RUhE},
{"sai",cmavo::SAI},

{"cei",cmavo::CEI},

{"ce'e",cmavo::CEhE},

{"co",cmavo::CO},

{"coi",cmavo::COI},
{"co'o",cmavo::COhO},
{"vi'o",cmavo::VIhO},
{"ta'a",cmavo::TAhA},
{"re'i",cmavo::REhI},
{"pe'u",cmavo::PEhU},
{"nu'e",cmavo::NUhE},
{"mu'o",cmavo::MUhO},
{"mi'e",cmavo::MIhE},
{"ki'e",cmavo::KIhE},
{"ke'o",cmavo::KEhO},
{"ju'i",cmavo::JUhI},
{"je'e",cmavo::JEhE},
{"fi'i",cmavo::FIhI},
{"fe'o",cmavo::FEhO},
{"be'e",cmavo::BEhE},

{"cu",cmavo::CU},

{"cu'e",cmavo::CUhE},
{"nau",cmavo::NAU},

{"da'o",cmavo::DAhO},

{"doi",cmavo::DOI},

{"do'u",cmavo::DOhU},

{"fa",cmavo::FA},
{"fe",cmavo::FE},
{"fi",cmavo::FI},
{"fo",cmavo::FO},
{"fu",cmavo::FU},
{"fai",cmavo::FAI},
{"fi'a",cmavo::FIhA},

{"be'a",cmavo::BEhA},
{"bu'u",cmavo::BUhU},
{"ca'u",cmavo::CAhU},
{"du'a",cmavo::DUhA},
{"fa'a",cmavo::FAhA},
{"ga'u",cmavo::GAhU},
{"ne'a",cmavo::NEhA},
{"ne'i",cmavo::NEhI},
{"ne'u",cmavo::NEhU},
{"ni'a",cmavo::NIhA},
{"pa'o",cmavo::PAhO},
{"re'o",cmavo::REhO},
{"ri'u",cmavo::RIhU},
{"ru'u",cmavo::RUhU},
{"te'e",cmavo::TEhE},
{"ti'a",cmavo::TIhA},
{"to'o",cmavo::TOhO},
{"vu'a",cmavo::VUhA},
{"ze'o",cmavo::ZEhO},
{"zo'a",cmavo::ZOhA},
{"zo'i",cmavo::ZOhI},
{"zu'a",cmavo::ZUhA},

{"fa'o",cmavo::FAhO},

{"fe'e",cmavo::FEhE},

{"fe'u",cmavo::FEhU},

{"fi'o",cmavo::FIhO},

{"foi",cmavo::FOI},

{"fu'e",cmavo::FUhE},

{"fu'o",cmavo::FUhO},

{"ga",cmavo::GA},
{"ge",cmavo::GE},
{"go",cmavo::GO},
{"gu",cmavo::GU},
{"ge'i",cmavo::GEhI},

{"ge'u",cmavo::GEhU},

{"gi",cmavo::GI},

{"gi'a",cmavo::GIhA},
{"gi'e",cmavo::GIhE},
{"gi'o",cmavo::GIhO},
{"gi'u",cmavo::GIhU},
{"gi'i",cmavo::GIhI},

{"goi",cmavo::GOI},
{"pe",cmavo::PE},
{"ne",cmavo::NE},
{"po",cmavo::PO},
{"po'e",cmavo::POhE},
{"po'u",cmavo::POhU},
{"no'u",cmavo::NOhU},

{"bu'a",cmavo::BUhA},
{"bu'e",cmavo::BUhE},
{"bu'i",cmavo::BUhI},
{"go'a",cmavo::GOhA},
{"go'e",cmavo::GOhE},
{"go'i",cmavo::GOhI},
{"go'o",cmavo::GOhO},
{"go'u",cmavo::GOhU},
{"co'e",cmavo::COhE},
{"du",cmavo::DU},
{"mo",cmavo::MO},
{"nei",cmavo::NEI},
{"no'a",cmavo::NOhA},

{"gu'a",cmavo::GUhA},
{"gu'e",cmavo::GUhE},
{"gu'o",cmavo::GUhO},
{"gu'u",cmavo::GUhU},
{"gu'i",cmavo::GUhI},

{".i",cmavo::I},

{"ja",cmavo::JA},
{"je",cmavo::JE},
{"jo",cmavo::JO},
{"ju",cmavo::JU},
{"je'i",cmavo::JEhI},

{"jai",cmavo::JAI},

{"ce",cmavo::CE},
{"ce'o",cmavo::CEhO},
{"fa'u",cmavo::FAhU},
{"pi'u",cmavo::PIhU},
{"jo'e",cmavo::JOhE},
{"jo'u",cmavo::JOhU},
{"joi",cmavo::JOI},
{"ju'e",cmavo::JUhE},
{"ku'a",cmavo::KUhA},

{"ke'e",cmavo::KEhE},

{"ke",cmavo::KE},

{"kei",cmavo::KEI},

{"ki",cmavo::KI},

{"ko'a",cmavo::KOhA},
{"ko'e",cmavo::KOhE},
{"ko'i",cmavo::KOhI},
{"ko'o",cmavo::KOhO},
{"ko'u",cmavo::KOhU},
{"fo'a",cmavo::FOhA},
{"fo'e",cmavo::FOhE},
{"fo'i",cmavo::FOhI},
{"fo'o",cmavo::FOhO},
{"fo'u",cmavo::FOhU},
{"vo'a",cmavo::VOhA},
{"vo'e",cmavo::VOhE},
{"vo'i",cmavo::VOhI},
{"vo'o",cmavo::VOhO},
{"vo'u",cmavo::VOhU},
{"ti",cmavo::TI},
{"ta",cmavo::TA},
{"tu",cmavo::TU},
{"ri",cmavo::RI},
{"ra",cmavo::RA},
{"ru",cmavo::RU},
{"mi",cmavo::MI},
{"do",cmavo::DO},
{"ko",cmavo::KO},
{"ma",cmavo::MA},
{"mi'o",cmavo::MIhO},
{"mi'a",cmavo::MIhA},
{"ma'a",cmavo::MAhA},
{"do'o",cmavo::DOhO},
{"zu'i",cmavo::ZUhI},
{"zi'o",cmavo::ZIhO},
{"zo'e",cmavo::ZOhE},
{"da",cmavo::DA},
{"de",cmavo::DE},
{"di",cmavo::DI},
{"do'i",cmavo::DOhI},
{"ce'u",cmavo::CEhU},
{"ke'a",cmavo::KEhA},
{"di'e",cmavo::DIhE},
{"de'e",cmavo::DEhE},
{"da'e",cmavo::DAhE},
{"di'u",cmavo::DIhU},
{"de'u",cmavo::DEhU},
{"da'u",cmavo::DAhU},

{"ku",cmavo::KU},

{"ku'o",cmavo::KUhO},

{"la",cmavo::LA},
{"la'i",cmavo::LAhI},
{"lai",cmavo::LAI},

{"ce'a",cmavo::CEhA},
{"lau",cmavo::LAU},
{"tau",cmavo::TAU},
{"zai",cmavo::ZAI},

{"la'e",cmavo::LAhE},
{"lu'a",cmavo::LUhA},
{"lu'e",cmavo::LUhE},
{"lu'i",cmavo::LUhI},
{"lu'o",cmavo::LUhO},
{"tu'a",cmavo::TUhA},
{"vu'i",cmavo::VUhI},

{"le",cmavo::LE},
{"lo",cmavo::LO},
{"lei",cmavo::LEI},
{"loi",cmavo::LOI},
{"le'i",cmavo::LEhI},
{"lo'i",cmavo::LOhI},
{"le'e",cmavo::LEhE},
{"lo'e",cmavo::LOhE},

{"le'u",cmavo::LEhU},

{"li",cmavo::LI},
{"me'o",cmavo::MEhO},

{"li'u",cmavo::LIhU},

{"lo'o",cmavo::LOhO},

{"lo'u",cmavo::LOhU},

{"lu",cmavo::LU},

{"lu'u",cmavo::LUhU},

{"me",cmavo::ME},

{"me'u",cmavo::MEhU},

{"mo'i",cmavo::MOhI},

{"ja'a",cmavo::JAhA},
{"na",cmavo::NA},

{"nai",cmavo::NAI},

{"je'a",cmavo::JEhA},
{"na'e",cmavo::NAhE},
{"no'e",cmavo::NOhE},
{"to'e",cmavo::TOhE},

{"ni'o",cmavo::NIhO},
{"no'i",cmavo::NOhI},

{"noi",cmavo::NOI},
{"poi",cmavo::POI},
{"voi",cmavo::VOI},

{"nu",cmavo::NU},
{"ni",cmavo::NI},
{"ka",cmavo::KA},
{"jei",cmavo::JEI},
{"si'o",cmavo::SIhO},
{"du'u",cmavo::DUhU},
{"li'i",cmavo::LIhI},
{"su'u",cmavo::SUhU},
{"mu'e",cmavo::MUhE},
{"pu'u",cmavo::PUhU},
{"za'i",cmavo::ZAhI},
{"zu'o",cmavo::ZUhO},

{"nu'i",cmavo::NUhI},

{"nu'u",cmavo::NUhU},

{"pe'e",cmavo::PEhE},

{"pu",cmavo::PU},
{"ca",cmavo::CA},
{"ba",cmavo::BA},

{"ra'o",cmavo::RAhO},

{"re'u",cmavo::REhU},
{"roi",cmavo::ROI},

{"sa",cmavo::SA},

{"se",cmavo::SE},
{"te",cmavo::TE},
{"ve",cmavo::VE},
{"xe",cmavo::XE},

{"sei",cmavo::SEI},
{"ti'o",cmavo::TIhO},

{"se'u",cmavo::SEhU},

{"si",cmavo::SI},

{"soi",cmavo::SOI},

{"su",cmavo::SU},

{"di'i",cmavo::DIhI},
{"na'o",cmavo::NAhO},
{"ru'i",cmavo::RUhI},
{"ta'e",cmavo::TAhE},

{"tei",cmavo::TEI},

{"to",cmavo::TO},
{"to'i",cmavo::TOhI},

{"toi",cmavo::TOI},

{"tu'e",cmavo::TUhE},

{"tu'u",cmavo::TUhU},

{".a'a",cmavo::AhA},
{".a'e",cmavo::AhE},
{".a'i",cmavo::AhI},
{".a'o",cmavo::AhO},
{".a'u",cmavo::AhU},
{".ai",cmavo::AI},
{".au",cmavo::AU},
{"ba'a",cmavo::BAhA},
{"ba'u",cmavo::BAhU},
{"be'u",cmavo::BEhU},
{"bi'u",cmavo::BIhU},
{"bu'o",cmavo::BUhO},
{"ca'e",cmavo::CAhE},
{"da'i",cmavo::DAhI},
{"dai",cmavo::DAI},
{"do'a",cmavo::DOhA},
{".e'a",cmavo::EhA},
{".e'e",cmavo::EhE},
{".e'i",cmavo::EhI},
{".e'o",cmavo::EhO},
{".e'u",cmavo::EhU},
{".ei",cmavo::EI},
{"fu'i",cmavo::FUhI},
{"ga'i",cmavo::GAhI},
{"ge'e",cmavo::GEhE},
{".i'a",cmavo::IhA},
{".i'e",cmavo::IhE},
{".i'i",cmavo::IhI},
{".i'o",cmavo::IhO},
{".i'u",cmavo::IhU},
{".ia",cmavo::IA},
{".ie",cmavo::IE},
{".ii",cmavo::II},
{".io",cmavo::IO},
{".iu",cmavo::IU},
{"ja'o",cmavo::JAhO},
{"je'u",cmavo::JEhU},
{"ji'a",cmavo::JIhA},
{"jo'a",cmavo::JOhA},
{"ju'a",cmavo::JUhA},
{"ju'o",cmavo::JUhO},
{"ka'u",cmavo::KAhU},
{"kau",cmavo::KAU},
{"ke'u",cmavo::KEhU},
{"ki'a",cmavo::KIhA},
{"ku'i",cmavo::KUhI},
{"la'a",cmavo::LAhA},
{"le'o",cmavo::LEhO},
{"li'a",cmavo::LIhA},
{"li'o",cmavo::LIhO},
{"mi'u",cmavo::MIhU},
{"mu'a",cmavo::MUhA},
{"na'i",cmavo::NAhI},
{".oi",cmavo::OI},
{".o'a",cmavo::OhA},
{".o'e",cmavo::OhE},
{".o'i",cmavo::OhI},
{".o'o",cmavo::OhO},
{".o'u",cmavo::OhU},
{"pa'e",cmavo::PAhE},
{"pau",cmavo::PAU},
{"pe'a",cmavo::PEhA},
{"pe'i",cmavo::PEhI},
{"po'o",cmavo::POhO},
{"ra'u",cmavo::RAhU},
{"re'e",cmavo::REhE},
{"ri'e",cmavo::RIhE},
{"ro'a",cmavo::ROhA},
{"ro'e",cmavo::ROhE},
{"ro'i",cmavo::ROhI},
{"ro'o",cmavo::ROhO},
{"ro'u",cmavo::ROhU},
{"ru'a",cmavo::RUhA},
{"sa'a",cmavo::SAhA},
{"sa'e",cmavo::SAhE},
{"sa'u",cmavo::SAhU},
{"se'a",cmavo::SEhA},
{"se'i",cmavo::SEhI},
{"se'o",cmavo::SEhO},
{"si'a",cmavo::SIhA},
{"su'a",cmavo::SUhA},
{"ta'o",cmavo::TAhO},
{"ta'u",cmavo::TAhU},
{"ti'e",cmavo::TIhE},
{"to'u",cmavo::TOhU},
{".u'a",cmavo::UhA},
{".u'e",cmavo::UhE},
{".u'i",cmavo::UhI},
{".u'o",cmavo::UhO},
{".u'u",cmavo::UhU},
{".ua",cmavo::UA},
{".ue",cmavo::UE},
{".ui",cmavo::UI},
{".uo",cmavo::UO},
{".uu",cmavo::UU},
{"va'i",cmavo::VAhI},
{"vu'e",cmavo::VUhE},
{"xu",cmavo::XU},
{"za'a",cmavo::ZAhA},
{"zo'o",cmavo::ZOhO},
{"zu'u",cmavo::ZUhU},
{"zi'a",cmavo::ZIhA},

{"vi",cmavo::VI},
{"va",cmavo::VA},
{"vu",cmavo::VU},

{"vau",cmavo::VAU},

{"ve'i",cmavo::VEhI},
{"ve'a",cmavo::VEhA},
{"ve'u",cmavo::VEhU},
{"ve'e",cmavo::VEhE},

{"vi'i",cmavo::VIhI},
{"vi'a",cmavo::VIhA},
{"vi'u",cmavo::VIhU},
{"vi'e",cmavo::VIhE},

{"vu'o",cmavo::VUhO},

{"xi",cmavo::XI},

{".y.",cmavo::Y},

{"pu'o",cmavo::PUhO},
{"ca'o",cmavo::CAhO},
{"ba'o",cmavo::BAhO},
{"co'a",cmavo::COhA},
{"co'i",cmavo::COhI},
{"co'u",cmavo::COhU},
{"de'a",cmavo::DEhA},
{"di'a",cmavo::DIhA},
{"mo'u",cmavo::MOhU},
{"za'o",cmavo::ZAhO},

{"ze'i",cmavo::ZEhI},
{"ze'a",cmavo::ZEhA},
{"ze'u",cmavo::ZEhU},
{"ze'e",cmavo::ZEhE},

{"zei",cmavo::ZEI},

{"zi",cmavo::ZI},
{"za",cmavo::ZA},
{"zu",cmavo::ZU},

{"zi'e",cmavo::ZIhE},

{"zo",cmavo::ZO},

{"la'o",cmavo::LAhO},
{"zoi",cmavo::ZOI},

{"zo'u",cmavo::ZOhU},

{"bi'e",cmavo::BIhE},

{"boi",cmavo::BOI},

{"fu'a",cmavo::FUhA},

{"ga'o",cmavo::GAhO},
{"ke'i",cmavo::KEhI},

{"jo'i",cmavo::JOhI},

{"ku'e",cmavo::KUhE},

{"mai",cmavo::MAI},
{"mo'o",cmavo::MOhO},

{"ma'o",cmavo::MAhO},

{"si'e",cmavo::SIhE},
{"va'e",cmavo::VAhE},
{"mei",cmavo::MEI},
{"moi",cmavo::MOI},
{"cu'o",cmavo::CUhO},

{"mo'e",cmavo::MOhE},

{"na'u",cmavo::NAhU},

{"ni'e",cmavo::NIhE},

{"nu'a",cmavo::NUhA},

{"pa",cmavo::PA},
{"re",cmavo::RE},
{"ci",cmavo::CI},
{"vo",cmavo::VO},
{"mu",cmavo::MU},
{"xa",cmavo::XA},
{"ze",cmavo::ZE},
{"bi",cmavo::BI},
{"so",cmavo::SO},
{"no",cmavo::NO},
{"dau",cmavo::DAU},
{"fei",cmavo::FEI},
{"gai",cmavo::GAI},
{"jau",cmavo::JAU},
{"rei",cmavo::REI},
{"vai",cmavo::VAI},
{"ro",cmavo::RO},
{"xo",cmavo::XO},
{"ce'i",cmavo::CEhI},
{"ci'i",cmavo::CIhI},
{"da'a",cmavo::DAhA},
{"du'e",cmavo::DUhE},
{"fi'u",cmavo::FIhU},
{"ji'i",cmavo::JIhI},
{"ka'o",cmavo::KAhO},
{"ki'o",cmavo::KIhO},
{"ma'u",cmavo::MAhU},
{"me'i",cmavo::MEhI},
{"mo'a",cmavo::MOhA},
{"ni'u",cmavo::NIhU},
{"no'o",cmavo::NOhO},
{"pai",cmavo::PAI},
{"pi",cmavo::PI},
{"pi'e",cmavo::PIhE},
{"ra'e",cmavo::RAhE},
{"rau",cmavo::RAU},
{"so'a",cmavo::SOhA},
{"so'e",cmavo::SOhE},
{"so'i",cmavo::SOhI},
{"so'o",cmavo::SOhO},
{"so'u",cmavo::SOhU},
{"su'e",cmavo::SUhE},
{"su'o",cmavo::SUhO},
{"te'o",cmavo::TEhO},
{"tu'o",cmavo::TUhO},
{"za'u",cmavo::ZAhU},

{"pe'o",cmavo::PEhO},

{"te'u",cmavo::TEhU},

{"vei",cmavo::VEI},

{"ve'o",cmavo::VEhO},

{"cu'a",cmavo::CUhA},
{"de'o",cmavo::DEhO},
{"fa'i",cmavo::FAhI},
{"fe'a",cmavo::FEhA},
{"fe'i",cmavo::FEhI},
{"fu'u",cmavo::FUhU},
{"ge'a",cmavo::GEhA},
{"gei",cmavo::GEI},
{"ju'u",cmavo::JUhU},
{"ne'o",cmavo::NEhO},
{"pa'i",cmavo::PAhI},
{"pi'a",cmavo::PIhA},
{"pi'i",cmavo::PIhI},
{"re'a",cmavo::REhA},
{"ri'o",cmavo::RIhO},
{"sa'i",cmavo::SAhI},
{"sa'o",cmavo::SAhO},
{"si'i",cmavo::SIhI},
{"su'i",cmavo::SUhI},
{"te'a",cmavo::TEhA},
{"va'a",cmavo::VAhA},
{"vu'u",cmavo::VUhU}
};

cmavo dettype(/*enum yytokentype sm,*/const char *const s) {
  for (int i=0;i<CMAVOCNT;i++) if (!strcmp(mahoste[i].l,s)) return mahoste[i].type;
}
